name: Booby-CI

on:
  push:
    branches: [master]
   
jobs:
  print-hello:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - run: echo "HelloCows"
      - uses: microsoft/setup-msbuild@v2
      - run: vcpkg integrate install
      - run: msbuild BlueFootedBooby.vcxproj -p:Configuration=Release -p:Platform=x64
  