name: Booby-CI

on:
  push:
    branches: [master]
   
jobs:
  build-release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - run: echo "HelloCows"
      - uses: microsoft/setup-msbuild@v2
      - run: vcpkg integrate install
      - run: msbuild BlueFootedBooby.vcxproj -p:Configuration=Release -p:Platform=x64
      - run: msbuild BlueFootedBoobyTests\BlueFootedBoobyTests.vcxproj -p:Configuration=Release -p:Platform=x64
       
      - name: Run Tests
        working-directory: BlueFootedBoobyTests
        run: ..\x64\Release\BlueFootedBoobyTests.exe

      - name: Upload Artifact if failed
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: golden-images
          path: BlueFootedBoobyTests/golden